FROM node:12.18.2-alpine as builder

WORKDIR /app

COPY . .

RUN yarn --frozen-lockfile --ignore-optional
RUN yarn build

FROM node:12.18.2-alpine

WORKDIR /app

COPY package.json ./
COPY yarn.lock .

RUN yarn --production=true --frozen-lockfile --ignore-optional

COPY --from=builder /app/dist ./dist

EXPOSE 5000

CMD ["yarn", "start:prod"]
